[build]
  command = "npm run build"
  functions = "functions-build"
  publish = "public"

[functions]
  node_bundler = "esbuild"
  included_files = ["*.js"]
  external_node_modules = ["websocket-polyfill", "nostr-tools", "node-fetch"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[dev]
  command = "npm run dev"
  port = 8888
  publish = "public"
